---
swagger: "2.0"
info:
  version: "v1"
  title: "Oauth2Authorization"
host: "localhost"
basePath: "/"
schemes:
- "https"
paths:
  /oauth2:
    get:
      description: "Root API."
      operationId: "rootGET"
      parameters: []
      responses:
        200:
          description: "Gets all root links."
          schema:
            $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
  /oauth2/authorize:
    get:
      description: "[CZ] Získání stránky s přihlášením a asociace k Oauth2. Po př\
        ihlášení\nvrazí na {callback_url}?code={auth_code}.\n\n\n[EN] Asociation with\
        \ Oauth2 and get the login page. After login returns\nto {callback_url}?code={auth_code}.\n"
      operationId: "oauth2AuthorizeGET"
      parameters:
      - name: "response_type"
        in: "query"
        description: "[CZ] Způsob návratu po autentizaci, musí být nastaveno na code.\n\
          \n[EN] Must be se to code.\n"
        required: true
        type: "string"
      - name: "client_id"
        in: "query"
        description: "[CZ] Vygenerované id aplikace (uživatelské jméno aplikace).\n\
          \n[EN] Generated application id (application user name).\n"
        required: true
        type: "string"
      - name: "redirect_uri"
        in: "query"
        description: "[CZ] Návratová adresa po autentizaci.\n\n[EN] Callback URL after\
          \ login.\n"
        required: true
        type: "string"
      - name: "scope"
        in: "query"
        description: "[CZ] Scope pro informace o uživateli, podporovaná je openid.\n\
          \n[EN] Authentication scope, openid only suported.\n"
        required: false
        type: "string"
      - name: "state"
        in: "query"
        description: "[CZ] Bezpečnostní hash, který oauth vrátí při úspěšném loginu\
          \ v\nparametru 'state'.\n\n[EN] Security hash, it will be returned to callback\
          \ url in 'state'\nparam.\n"
        required: false
        type: "string"
      responses:
        200:
          description: "Description"
      x-auth-type: "Application & Application User"
      x-throttling-tier: "Unlimited"
      x-swagger-router-controller: "Default"
  /oauth2/revoke:
    post:
      description: "[CZ] Zrušení platnosti tokenu.\n\n[EN] Token revocation.\n"
      operationId: "oauth2RevokePOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "text/html"
      parameters:
      - name: "token"
        in: "formData"
        description: "[CZ] Přístupový token.\n\n[EN] Access token.\n"
        required: false
        type: "string"
      - name: "token_type_hint"
        in: "formData"
        description: "[CZ] Typ předaného tokenu.\n\n[EN] Token type.\n"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/out-post-oauth2-token-400"
          examples:
            application/json:
            - error: "invalid_client"
              error_description: "Client Authentication failed."
      security:
      - Basic: []
      x-auth-type: "Application & Application User"
      x-throttling-tier: "Unlimited"
      x-swagger-router-controller: "Default"
  /oauth2/token:
    post:
      description: "[CZ] Manipulace s tokenem - vyžádání, obnova.\n\n[EN] Token request,\
        \ renewal.\n"
      operationId: "oauth2TokenPOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "grant_type"
        in: "formData"
        description: "[CZ] Typ operace - podporované jsou\n    - authorization_code\
          \ - získání tokenu pomocí OTP získaného přes authorize endpoint.\n    -\
          \ password - získání tokenu přes jméno a heslo\n    - refresh_token - obnova\
          \ tokenu pomocí refresh token\n\n[EN] Grant type - supported\n    - authorization_code\
          \ - get the token though OTP from authorize endpoint\n    - password - get\
          \ the token by providing username and password\n    - refresh_token - token\
          \ renewal though refresh token\n"
        required: true
        type: "string"
      - name: "code"
        in: "formData"
        description: "[CZ] Jednorázové heslo obdržené při návratu na callback_url,\
          \ povinný pouze při authorization_code operaci.\n\n[EN] One type password\
          \ received by returning to callback_url, required with authorization_code\
          \ grant.\n"
        required: false
        type: "string"
      - name: "redirect_uri"
        in: "formData"
        description: "[CZ] Callback url definovaná pro aplikaci, povinná při authorization_code\
          \ operaci.\n\n[EN] Callback url defined for application, required with authorization_code\
          \ grant.\n"
        required: false
        type: "string"
      - name: "client_id"
        in: "formData"
        description: "[CZ] Vygenerované ID aplikace, požadované pro každou operaci\
          \ pokud není použita Basic authorization.\n\n[EN] Generated appliaction\
          \ ID, required for every grant if Basic authorization not preset.\n"
        required: true
        type: "string"
      - name: "client_secret"
        in: "formData"
        description: "[CZ] Heslo pro aplikaci, nepožadováno při operaci password.\n\
          \n[EN] Application password, not required with password grant.\n"
        required: false
        type: "string"
      - name: "username"
        in: "formData"
        description: "[CZ] Uživatelské jméno povinné při operaci password.\n\n[EN]\
          \ Username required with password grant.\n"
        required: false
        type: "string"
      - name: "password"
        in: "formData"
        description: "[CZ] Uživatelské heslo povinné při operaci password.\n\n[EN]\
          \ User password required with password grant.\n"
        required: false
        type: "string"
      - name: "scope"
        in: "formData"
        description: "[CZ] Rozsah autorizace povinný pro operaci password.\n\n[EN]\
          \ Authorization scope required with password grant.\n"
        required: false
        type: "string"
      - name: "refresh_token"
        in: "formData"
        description: "[CZ] Refresh token povinný při operaci refresh_token obdržený\
          \ s access tokenem.\n\n[EN] Refresh token required with refresh_token grant\
          \ received earlier with access token.\n"
        required: false
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/out-post-oauth-token"
          examples:
            application/json:
            - scope: "openid"
              token_type: "Bearer"
              expires_in: 3600
              refresh_token: "6583215d3a2aedf6268e923d15fcb03e"
              id_token: "eyJhbGciOiJSUzI1NiJ9.eyJhdXRoX3RpbWUiOjE0NjQ3OTA1MjksImV4cCI6MTQ2NDc5NDEyOSwiYXpwIjoicWNPT2tQcXJJM1hWelpveVBoVlBCWVZPSExjYSIsImF0X2hhc2giOiJGSmk0UHB0X2ZYRHVjUWp5VXZmWHZBIiwiYXVkIjpbInFjT09rUHFySTNYVnpab3lQaFZQQllWT0hMY2EiXSwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwiaWF0IjoxNDY0NzkwNTI5fQ.EZukbnCEvT1Yu8d3hXuRDAD4NUxRBh84E8JGwrpyj6j_s0C8V1jifRj37_UtlkzQEYlM0UfXUrpD_cK_FYwYb-rR1c1oeTIDGKyhxeqJ1NlGpH-_E2038NSpj0LlQhzKLMBSvwwuZcoyxFINrWeqGlcC0j2NHBNVMA65G0ID2hs"
              access_token: "46d0311c987c5af757d3f264c1fd2545"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/out-post-oauth2-token-400"
          examples:
            application/json:
            - error: "invalid_grant"
              error_description: "Provided Authorization Grant is invalid"
        401:
          description: "Unauthorized"
          schema:
            $ref: "#/definitions/out-post-oauth2-token-400"
          examples:
            application/json:
            - error: "invalid_client"
              error_description: "Client Authentication failed."
      security:
      - Basic: []
      x-auth-type: "Application & Application User"
      x-throttling-tier: "Unlimited"
      x-swagger-router-controller: "Default"
  /oauth2/userinfo:
    get:
      description: "[CZ] Informace o přihlášeném uživateli.\n\n[EN] Logged in user\
        \ info.\n"
      operationId: "oauth2UserinfoGET"
      produces:
      - "application/json"
      parameters:
      - name: "schema"
        in: "query"
        description: "[CZ] Schéma uživatelských atributů.\n\n[EN] User attribute schema.\n"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/out-get-oauth2-userinfo"
          examples:
            application/json:
            - sub: "B15209@eon-distribuce.carbon"
              organization: "EBSCZ"
              email: "bretislav.kabele@eon.com"
              roles: "Application/partnersky-portal,Application/B15209_DefaultApplication_PRODUCTION,Application/nEMS,Application/partnersky-portal/ECP,Application/nEMS2,Application/nEMS/GEOF,Application/nEMS3,Application/test,Application/nEMS4,Application/partnersky-portal/BOZP,Application/test-csharp,Application/aaaaa,admin,Application/partnersky-portal/all,Internal/everyone,Application/registrace"
              surname: "Kábele"
              firstname: "Břetislav"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/out-post-oauth2-token-400"
          examples:
            application/json:
            - error: "invalid_client"
              error_description: "Client Authentication failed."
      security:
      - Bearer:
        - "authorize"
      x-auth-type: "Application & Application User"
      x-throttling-tier: "Unlimited"
      x-swagger-router-controller: "Default"
securityDefinitions:
  Basic:
    description: "[CZ] Autorizace pomocí app_id (uživatelské jméno) a app_secret (heslo),\n\
      nemusí být přítomna, pokud se parametry vloží do body.\n\n\n[EN] Authorization\
      \ with app_id (username) and app_secret (password), it do\nnot have to passed\
      \ if parameters are present in body.\n"
    type: "basic"
  Bearer:
    description: "[CZ] Oauth2 autentizace pomocí přístupového tokenu.\n\n[EN] Oauth2\
      \ autentization with access token.\n"
    type: "oauth2"
    authorizationUrl: "https://localhost/oauth2/authorize"
    tokenUrl: "https://localhost/oauth2/token"
    flow: "accessCode"
    scopes:
      authorize: "authorize users"
definitions:
  out-get-oauth2-userinfo:
    type: "object"
    properties:
      email:
        type: "string"
      firstname:
        type: "string"
      organization:
        type: "string"
      roles:
        type: "string"
      sub:
        type: "string"
      surname:
        type: "string"
  out-post-oauth-token:
    type: "object"
    properties:
      access_token:
        type: "string"
      expires_in:
        type: "number"
      id_token:
        type: "string"
      refresh_token:
        type: "string"
      scope:
        type: "string"
      token_type:
        type: "string"
  out-post-oauth2-token-400:
    type: "object"
    properties:
      error:
        type: "string"
      error_description:
        type: "string"
  inline_response_200:
    properties:
      links:
        type: "array"
        description: "Links to payments (invoice, pre-payments), contract, partner\
          \ and consumption.\n'rel' values:\n  - installations\n  - services\n  -\
          \ auto_complete\n  - change-password\n"
        items:
          $ref: "#/definitions/Link"
  Link:
    type: "object"
    required:
    - "href"
    - "rel"
    properties:
      rel:
        type: "string"
        enum:
        - "invoices"
        - "pre-payments"
        - "payments"
        - "partner"
        - "contract"
        - "consumption"
        - "bank"
        - "next"
        - "hdo-times"
        - "online-payment"
        - "edit-address"
        - "edit-mobile"
        - "edit-email"
        - "edit-pre-payment"
        - "add-meter-read"
        - "add-ebill"
        - "change-password"
        - "auto_complete"
        - "installations"
        - "services"
      href:
        type: "string"
